import React from 'react';
import {
  Box,
  Typography,
  Chip,
  Badge,
  Button,
  Paper,
  Grid,
  Tooltip
} from '@mui/material';
import {
  Collections as TrainingIcon,
  Copyright as RightsIcon,
  Upload as UploadIcon,
  Edit as EditIcon
} from '@mui/icons-material';
import { layerConfig } from '../../api/layerConfig';

import { Asset as GlobalAsset } from '../../types/asset.types';

// Local interface for simplified assets
interface SimpleAsset {
  id?: string;
  name: string;
  address?: string;
  status?: 'pending' | 'complete' | 'incomplete';
}

interface AutoGeneratedAssetReferencesProps {
  trainingAsset: GlobalAsset | SimpleAsset | null;
  rightsAsset: GlobalAsset | SimpleAsset | null;
  onUploadTrainingData?: () => void;
  onEditRightsData?: () => void;
  showButtons?: boolean; // Whether to show the Upload/Edit buttons
  showHelperText?: boolean; // Whether to show the helper text at the bottom
}

const AutoGeneratedAssetReferences: React.FC<AutoGeneratedAssetReferencesProps> = ({
  trainingAsset,
  rightsAsset,
  onUploadTrainingData,
  onEditRightsData,
  showButtons = true,
  showHelperText = true
}) => {
  if (!trainingAsset && !rightsAsset) {
    return null;
  }

  return (
    <Paper sx={{ p: 2, mt: 3, mb: 3 }}>
      <Typography variant="subtitle1" gutterBottom>
        Auto-generated Related Assets
      </Typography>
      
      <Grid container spacing={2}>
        {trainingAsset && (
          <Grid item xs={12} md={6}>
            <Box sx={{ 
              display: 'flex', 
              alignItems: 'center', 
              justifyContent: 'space-between',
              p: 1,
              border: '1px solid',
              borderColor: 'divider',
              borderRadius: 1
            }}>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <TrainingIcon 
                  sx={{ 
                    color: layerConfig['T'].color,
                    mr: 1
                  }} 
                />
                <Box>
                  <Typography variant="body2" fontWeight="medium">
                    Training Data Asset
                  </Typography>
                  <Tooltip title={trainingAsset.name}>
                    <Typography 
                      variant="body2" 
                      color="text.secondary" 
                      sx={{ 
                        maxWidth: '200px', 
                        overflow: 'hidden', 
                        textOverflow: 'ellipsis', 
                        whiteSpace: 'nowrap' 
                      }}
                    >
                      {trainingAsset.address || ('nnaAddress' in trainingAsset ? trainingAsset.nnaAddress : '') || trainingAsset.name}
                    </Typography>
                  </Tooltip>
                </Box>
              </Box>
              
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <Badge
                  badgeContent="Auto-generated"
                  color="primary"
                  sx={{ mr: 1 }}
                />
                {showButtons && onUploadTrainingData && (
                  <Button
                    size="small"
                    variant="outlined"
                    startIcon={<UploadIcon />}
                    onClick={onUploadTrainingData}
                    sx={{ ml: 1 }}
                  >
                    Upload
                  </Button>
                )}
              </Box>
            </Box>
          </Grid>
        )}
        
        {rightsAsset && (
          <Grid item xs={12} md={6}>
            <Box sx={{ 
              display: 'flex', 
              alignItems: 'center', 
              justifyContent: 'space-between',
              p: 1,
              border: '1px solid',
              borderColor: 'divider',
              borderRadius: 1
            }}>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <RightsIcon 
                  sx={{ 
                    color: layerConfig['R'].color,
                    mr: 1
                  }} 
                />
                <Box>
                  <Typography variant="body2" fontWeight="medium">
                    Rights Data Asset
                  </Typography>
                  <Tooltip title={rightsAsset.name}>
                    <Typography 
                      variant="body2" 
                      color="text.secondary" 
                      sx={{ 
                        maxWidth: '200px', 
                        overflow: 'hidden', 
                        textOverflow: 'ellipsis', 
                        whiteSpace: 'nowrap' 
                      }}
                    >
                      {rightsAsset.address || ('nnaAddress' in rightsAsset ? rightsAsset.nnaAddress : '') || rightsAsset.name}
                    </Typography>
                  </Tooltip>
                </Box>
              </Box>
              
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <Badge
                  badgeContent="Auto-generated"
                  color="secondary"
                  sx={{ mr: 1 }}
                />
                {showButtons && onEditRightsData && (
                  <Button
                    size="small"
                    variant="outlined"
                    startIcon={<EditIcon />}
                    onClick={onEditRightsData}
                    sx={{ ml: 1 }}
                  >
                    Edit
                  </Button>
                )}
              </Box>
            </Box>
          </Grid>
        )}
      </Grid>
      
      {showHelperText && (
        <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
          These assets are automatically generated to manage training data and rights information.
        </Typography>
      )}
    </Paper>
  );
};

export default AutoGeneratedAssetReferences;