name: Build and Test

on:
  push:
    branches:
      - main
      - stable-frontend
  pull_request:
    branches:
      - main
      - stable-frontend

env:
  REACT_APP_API_URL: "https://registry.reviz.dev/api"
  REACT_APP_REAL_API_URL: "https://registry.reviz.dev/api"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
          REACT_APP_REAL_API_URL: ${{ env.REACT_APP_REAL_API_URL }}
        
      - name: Run Tests
        run: npm test -- --passWithNoTests